apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-1724 
  janus-idp.io/tekton: java-1724
  backstage.io/kubernetes-id: java-1724
  backstage.io/kubernetes-namespace: rhtap-organization-app 
  app.kubernetes.io/part-of: java-1724
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  